# Generated by Django 2.2.1 on 2019-06-07 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('duties', '0004_auto_20190607_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duty',
            name='behalf',
        ),
        migrations.AddField(
            model_name='duty',
            name='debtee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duty_debt_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
